<?php

return [
    "en" => [
        "name" => "Tiếng Anh",
        "name_by_language" => "English",
        "area" => "Toàn cầu",
        "scope" => "Ngôn ngữ phổ biến toàn cầu",
        "currency" => "USD",
        "currency_code" => "$",
        "money_value" => "1",
        "decimal_places" => 2,
        "key" => "en",
        "latin"     => true,
        "flag_join_left_to_right" => false,
        "flag_has_space_in_content" => true,
        "dir"       => "ltr",
        "slug_page_premium_wallpaper" => "phone-wallpapers",
        "data"      => [
            "home"          => "Home",
            "about_us"      => "About us",
            "event"             => "Event",
            "support"           => "Support",
            "connect_with_us"   => "Connect with us",
            "table_of_contents" => "Table of Contents",
            "photo_set"         => "Photo set",
            "share"             => "Share",
            "no_suitable_results_found" => "No suitable results found",
            "cart"              => "Cart",
            "your_cart_is_empty"    => "Your cart is empty",
            "continue_shopping"     => "Continue shopping",
            "full_set"          => "Full set",
            "image"             => "Image",
            "options"           => "Options",
            "product_guide_after_payment"   => "<div>After payment, you will receive the original image directly and via email for download and use.</div>",
            "suggestions_for_you"   => "Suggestions for you!",
            "each_image"        => "Each image",
            "each_set"          => "Each set",
            "propose" => "Propose",
            "favourite" => "Favourite",
            "newest" => "Newest",
            "oldest" => "Oldest",
            "browse_by" => "Browse by ",
            "sort_by" => "Sort by ",
            "filter_by" => "Filter by ",
            "filter_by_themes" => "Filter by Themes",
            "filter_by_styles" => "Filter by Styles",
            "filter_by_events" => "Filter by Events",
            "advanced_filter" => "Advanced Filter",
            "all" => "All",
            "added_to_cart" => "Added to Cart!",
            "view_cart" => "View Cart",
            "add_to_cart" => "Add to Cart",
            "buy_now" => "Buy Now",
            "undefined" => "Undefined",
            "total" => "Total",
            "remove_item_in_cart" => "Remove Item from Cart",
            "product_list" => "Product List",
            "product" => "Product",
            "unit_price" => "Unit Price",
            "total_price" => "Total Price",
            "payment" => "Payment",
            "information" => "Information",
            "email_prompt" => "If you enter your email, you will receive an additional copy for storage.",
            "email_receive" => "Email for receiving images",
            "payment_method" => "Payment Method",
            "fee" => "Fee",
            "payment_fee" => "Payment Fee",
            'view_all'  => 'View all',
            'login_name_com_vn' => 'Login Name.com.vn',
            'login_email' => 'Login Email',
            'password' => 'Password',
            'remember_me' => 'Remember me',
            'login' => 'Login',
            'or_login_with' => 'Or login with',
            'support' => 'Support',
            'download_guide' => 'Download Guide',
            'account_information' => 'Account Information',
            'my_downloads' => 'My Downloads',
            'logout' => 'Logout',
            'article' => "Article",
            'featured_articles' => 'Featured Articles',
            'news_category' => 'News Category',
            'payment_successful' => "Payment successful!",
            'thank_you_message' => "Thank you for supporting Name.com.vn. Your image is below, or you can check your email to download the image.",
            'order_id' => "Order ID",
            'email' => "Email",
            'click_to_download' => "Click to download",
            'step_1_buy_now' => "Step 1: Please enter your email.",
            'note_fill_email' => "* If you enter an email, an additional copy will be sent for storage.",
            'step_2_buy_now' => "Step 2: Choose a payment method.",
            'what_do_you_want_to_find_today' => "What do you want to find today?",
            'search' => "Search",
            /* xác nhận đơn hàng */
            'order_confirmation' => 'Order Confirmation',
            'thank_you_message_email' => 'Thank you for completing your order! Your wallpaper is ready to use.',
            'hello' => 'Hello',
            'purchase_date' => 'Purchase Date',
            'download_instructions' => 'You can download the wallpaper collection in the following ways:',
            'direct_download' => 'Direct download through the links below:',
            'sincerely' => 'Sincerely!',
            'login_instruction_message_email' => 'Or log in to <a href="https://name.com.vn" style="color: #006d57; text-decoration: none; font-weight: 700;">Name.com.vn</a> with your email and go to the <strong>"My Downloads"</strong> section.',
            'support_contact_message_email' => 'If you have any questions or need support, please contact us via email at <a href="mailto:wallpaperdienthoai@gmail.com" style="color: #006d57; text-decoration: none; font-weight: 700;">wallpaperdienthoai@gmail.com</a>.',
            'wish_message_email' => 'We wish you a great experience with your new wallpaper collection!',
            /* custom */
            "wallpaper_theme"  => [
                "name"  => "Wallpaper Theme",
                "topgirl"  => "Photo Theme",
                "topanime"  => "Photo Theme",
            ],
            "wallpaper_style"   => [
                "name"  => "Wallpaper Style",
                "topgirl"  => "Photo Style",
                "topanime"  => "Photo Style",
            ],
            "free_wallpaper"    => [
                "name"  => "Free Wallpaper",
                "topgirl"  => "Free Photo",
                "topanime"  => "Free Photo",
            ],
            "phone_wallpaper"         => [
                "name"  => "Phone Wallpaper ",
                "topgirl"  => "Beautiful Girl Images ",
                "topanime"  => "Beautiful Girl Images ",
            ],
            "product_description"   => [
                "name"  => "<div>Transform your phone's wallpaper into a work of art with this stunning photo collection! Bring a fresh and unique style to your phone.</div>
                                <ul>
                                    <li>High resolution: 1440x3360, ensuring sharp images with every detail.</li>
                                    <li>Perfectly compatible with all types of phone screens.</li>
                                    <li>Easy and quick download in just a few simple steps.</li>
                                    <li>Usage rights included, feel free to share with your friends.</li>
                                </ul>
                                <div>Download now and experience the exciting difference on your phone's screen!</div>",
                "topgirl"  => "<div>Add some color and unique style to your cute phone with this beautiful phone wallpaper set.</div>
                                            <ul>
                                                <li>Resolution: 1440x3360</li>
                                                <li>Compatible with all phone screens.</li>
                                            </ul>
                                            <div>Download and apply it directly to your phone screen to experience it!</div>",
                "topanime"  => "<div>Add some color and unique style to your cute phone with this beautiful phone wallpaper set.</div>
                                            <ul>
                                                <li>Resolution: 1440x3360</li>
                                                <li>Compatible with all phone screens.</li>
                                            </ul>
                                            <div>Download and apply it directly to your phone screen to experience it!</div>",
            ],
            "wallpaper_by_themes" => [
                "name"  => "Wallpapers by Themes",
                "topgirl"  => "Beautiful Girl Photos by Themes",
                "topanime"  => "Beautiful Girl Photos by Themes",
            ],
            "wallpaper_by_styles" => [
                "name"  => "Wallpapers by Styles",
                "topgirl"  => "Beautiful Girl Photos by Styles",
                "topanime"  => "Beautiful Girl Photos by Styles",
            ],
            "wallpaper_by_events" => [
                "name"  => "Wallpapers by Events",
                "topgirl"  => "Beautiful Girl Photos by Events",
                "topanime"  => "Beautiful Girl Photos by Events",
            ],
            "list_type_search" => [
                'wrpfvietnam' => [
                    'category_info' => 'Category',
                    'paid_wallpaper' => 'Paid Wallpapers',
                    'free_wallpaper' => 'Free Wallpapers',
                    'article' => 'Article',
                ],
                'topgirl' => [
                    'category_info' => 'Category',
                    'paid_wallpaper' => 'Paid Wallpapers',
                    'free_wallpaper' => 'Free Wallpapers',
                    'article' => 'Article',
                ],
                'topanime' => [
                    'category_info' => 'Category',
                    'paid_wallpaper' => 'Paid Wallpapers',
                    'free_wallpaper' => 'Free Wallpapers',
                    'article' => 'Article',
                ],
            ],
            "copyright" => [
                "name"  => "Copyright ® ".date('Y')." <a href='{{ env('APP_URL') }}/{{ \$language }}' aria-label='Name'>Name</a>. Designed and developed by Pham Van Phu. All rights reserved.",
            ]
        ]
    ],
    "zh" => [
        "name" => "Tiếng Trung",
        "name_by_language" => "中文 (Zhōngwén)",
        "area" => "Trung Quốc, Đài Loan, Singapore",
        "scope" => "Ngôn ngữ phổ biến toàn cầu",
        "currency" => "CNY",
        "currency_code" => "¥",
        "money_value" => "7",
        "decimal_places" => 2,
        "key" => "zh",
        "latin"     => false,
        "flag_join_left_to_right" => true,
        "flag_has_space_in_content" => false,
        "dir"       => "ltr",
        "slug_page_premium_wallpaper" => "手机壁纸",
        "data" => [
            "home" => "首页",
            "about_us" => "关于我们",
            "event" => "活动",
            "support" => "支持",
            "connect_with_us" => "与我们联系",
            "table_of_contents" => "目录",
            "photo_set" => "照片集",
            "share" => "分享",
            "no_suitable_results_found" => "未找到合适的结果",
            "cart" => "购物车",
            "your_cart_is_empty" => "您的购物车是空的",
            "continue_shopping" => "继续购物",
            "full_set" => "整套",
            "image" => "图片",
            "options" => "选项",
            "product_guide_after_payment" => "<div>付款后，您将直接通过电子邮件收到原始图像进行下载和使用。</div>",
            "suggestions_for_you" => "为您推荐!",
            "each_image" => "每张图片",
            "each_set" => "每套",
            "propose" => "提议",
            "favourite" => "收藏",
            "newest" => "最新",
            "oldest" => "最旧",
            "browse_by" => "浏览",
            "sort_by" => "排序",
            "filter_by" => "筛选",
            "filter_by_themes" => "按主题筛选",
            "filter_by_styles" => "按风格筛选",
            "filter_by_events" => "按活动筛选",
            "advanced_filter" => "高级筛选",
            "all" => "全部",
            "added_to_cart" => "已加入购物车!",
            "view_cart" => "查看购物车",
            "add_to_cart" => "加入购物车",
            "buy_now" => "立即购买",
            "undefined" => "未定义",
            "total" => "总计",
            "remove_item_in_cart" => "从购物车中移除商品",
            "product_list" => "产品列表",
            "product" => "产品",
            "unit_price" => "单价",
            "total_price" => "总价",
            "payment" => "付款",
            "information" => "信息",
            "email_prompt" => "如果您输入电子邮件，您将收到一份额外的副本以供存储。",
            "email_receive" => "接收图片的电子邮件",
            "payment_method" => "支付方式",
            "fee" => "费用",
            "payment_fee" => "支付费用",
            'view_all' => '查看全部',
            'login_name_com_vn' => '登录 Name.com.vn',
            'login_email' => '登录邮箱',
            'password' => '密码',
            'remember_me' => '记住我',
            'login' => '登录',
            'or_login_with' => '或通过以下方式登录',
            'support' => '支持',
            'download_guide' => '下载指南',
            'account_information' => '账户信息',
            'my_downloads' => '我的下载',
            'logout' => '退出登录',
            'article' => "文章",
            'featured_articles' => '精选文章',
            'news_category' => '新闻分类',
            'payment_successful' => "支付成功！",
            'thank_you_message' => "感谢您对 Name.com.vn 的支持。您的图片在下面，您也可以通过电子邮件访问下载图片。",
            'order_id' => "订单编号",
            'email' => "电子邮件",
            'click_to_download' => "点击下载",
            'step_1_buy_now' => "步骤1：请您输入邮箱。",
            'note_fill_email' => "* 如果输入邮箱，将会发送一份副本以便存档。",
            'step_2_buy_now' => "步骤2：选择付款方式。",
            'what_do_you_want_to_find_today' => "你今天想找什么？",
            'search' => "搜索",
            /* xác nhận đơn hàng */
            'order_confirmation' => '订单确认',
            'thank_you_message_email' => '感谢您完成订单！您的壁纸已准备就绪。',
            'hello' => '你好',
            'purchase_date' => '购买日期',
            'download_instructions' => '您可以通过以下方式下载壁纸合集：',
            'direct_download' => '通过以下链接直接下载：',
            'sincerely' => '谨上!',
            'login_instruction_message_email' => '或者使用您的电子邮件登录 <a href="https://name.com.vn" style="color: #006d57; text-decoration: none; font-weight: 700;">Name.com.vn</a> 并进入 <strong>"我的下载"</strong> 部分。',
            'support_contact_message_email' => '如果您有任何问题或需要支持，请通过电子邮件与我们联系：<a href="mailto:wallpaperdienthoai@gmail.com" style="color: #006d57; text-decoration: none; font-weight: 700;">wallpaperdienthoai@gmail.com</a>。',
            'wish_message_email' => '祝您在使用新壁纸合集时有愉快的体验！',
            /* custom */
            "wallpaper_theme" => [
                "name" => "壁纸主题",
                "topgirl" => "照片主题",
                "topanime" => "照片主题",
            ],
            "wallpaper_style" => [
                "name" => "壁纸风格",
                "topgirl" => "照片风格",
                "topanime" => "照片风格",
            ],
            "free_wallpaper" => [
                "name" => "免费壁纸",
                "topgirl" => "免费照片",
                "topanime" => "免费照片",
            ],
            "phone_wallpaper" => [
                "name" => "手机壁纸",
                "topgirl" => "漂亮女孩图片",
                "topanime" => "漂亮女孩图片",
            ],
            "product_description" => [
                "name" => "<div>用这套令人惊叹的照片集将您的手机壁纸变成艺术品！为您的手机带来全新的独特风格。</div>
                            <ul>
                                <li>高分辨率：1440x3360，确保每个细节都清晰。</li>
                                <li>完美兼容所有类型的手机屏幕。</li>
                                <li>只需几个简单步骤即可轻松快速下载。</li>
                                <li>包含使用权，可自由与朋友分享。</li>
                            </ul>
                            <div>立即下载，体验手机屏幕上的惊人变化！</div>",
                "topgirl" => "<div>用这套美丽的手机壁纸为您的可爱手机增添一些色彩和独特风格。</div>
                                <ul>
                                    <li>分辨率：1440x3360</li>
                                    <li>兼容所有手机屏幕。</li>
                                </ul>
                                <div>下载并直接应用于您的手机屏幕以体验！</div>",
                "topanime" => "<div>用这套美丽的手机壁纸为您的可爱手机增添一些色彩和独特风格。</div>
                                <ul>
                                    <li>分辨率：1440x3360</li>
                                    <li>兼容所有手机屏幕。</li>
                                </ul>
                                <div>下载并直接应用于您的手机屏幕以体验！</div>",
            ],
            "wallpaper_by_themes" => [
                "name" => "按主题分类的壁纸",
                "topgirl" => "按主题分类的漂亮女孩照片",
                "topanime" => "按主题分类的漂亮女孩照片",
            ],
            "wallpaper_by_styles" => [
                "name" => "按风格分类的壁纸",
                "topgirl" => "按风格分类的漂亮女孩照片",
                "topanime" => "按风格分类的漂亮女孩照片",
            ],
            "wallpaper_by_events" => [
                "name" => "按活动分类的壁纸",
                "topgirl" => "按活动分类的漂亮女孩照片",
                "topanime" => "按活动分类的漂亮女孩照片",
            ],
            "list_type_search" => [
                'wrpfvietnam' => [
                    'category_info' => '类别',
                    'paid_wallpaper' => '付费壁纸',
                    'free_wallpaper' => '免费壁纸',
                    'article' => '文章',
                ],
                'topgirl' => [
                    'category_info' => '类别',
                    'paid_wallpaper' => '付费壁纸',
                    'free_wallpaper' => '免费壁纸',
                    'article' => '文章',
                ],
                'topanime' => [
                    'category_info' => '类别',
                    'paid_wallpaper' => '付费壁纸',
                    'free_wallpaper' => '免费壁纸',
                    'article' => '文章',
                ],
            ],
            "copyright" => [
                "name"  => "版权所有 ® ".date('Y')." <a href='{{ env('APP_URL') }}/{{ \$language }}' aria-label='Name'>Name</a>。由范文富设计和开发。版权所有。",
            ]
        ]
    ],
    "es" => [
        "name" => "Tiếng Tây Ban Nha",
        "name_by_language" => "Español",
        "area" => "Tây Ban Nha, Mỹ Latinh",
        "scope" => "Ngôn ngữ phổ biến toàn cầu",
        "currency" => "EUR",
        "currency_code" => "€",
        "money_value" => "0.85",
        "decimal_places" => 2,
        "key" => "es",
        "latin"     => true,
        "flag_join_left_to_right" => true,
        "flag_has_space_in_content" => true,
        "dir"       => "ltr",
        "slug_page_premium_wallpaper" => "fondos-de-pantalla-para-telefonos",
        "data" => [
            "home" => "Inicio",
            "about_us" => "Sobre nosotros",
            "event" => "Evento",
            "support" => "Soporte",
            "connect_with_us" => "Conéctate con nosotros",
            "table_of_contents" => "Tabla de contenidos",
            "photo_set" => "Conjunto de fotos",
            "share" => "Compartir",
            "no_suitable_results_found" => "No se encontraron resultados adecuados",
            "cart" => "Carrito",
            "your_cart_is_empty" => "Tu carrito está vacío",
            "continue_shopping" => "Continuar comprando",
            "full_set" => "Conjunto completo",
            "image" => "Imagen",
            "options" => "Opciones",
            "product_guide_after_payment" => "<div>Después del pago, recibirás la imagen original directamente y por correo electrónico para descargar y usar.</div>",
            "suggestions_for_you" => "¡Sugerencias para ti!",
            "each_image" => "Cada imagen",
            "each_set" => "Cada conjunto",
            "propose" => "Proponer",
            "favourite" => "Favorito",
            "newest" => "Más nuevo",
            "oldest" => "Más antiguo",
            "browse_by" => "Navegar por ",
            "sort_by" => "Ordenar por ",
            "filter_by" => "Filtrar por ",
            "filter_by_themes" => "Filtrar por temas",
            "filter_by_styles" => "Filtrar por estilos",
            "filter_by_events" => "Filtrar por eventos",
            "advanced_filter" => "Filtro avanzado",
            "all" => "Todo",
            "added_to_cart" => "¡Agregado al carrito!",
            "view_cart" => "Ver carrito",
            "add_to_cart" => "Añadir al carrito",
            "buy_now" => "Comprar ahora",
            "undefined" => "Indefinido",
            "total" => "Total",
            "remove_item_in_cart" => "Eliminar artículo del carrito",
            "product_list" => "Lista de productos",
            "product" => "Producto",
            "unit_price" => "Precio unitario",
            "total_price" => "Precio total",
            "payment" => "Pago",
            "information" => "Información",
            "email_prompt" => "Si introduces tu correo electrónico, recibirás una copia adicional para almacenamiento.",
            "email_receive" => "Correo electrónico para recibir imágenes",
            "payment_method" => "Método de pago",
            "fee" => "Tarifa",
            "payment_fee" => "Tarifa de pago",
            'view_all' => 'Ver todo',
            'login_name_com_vn' => 'Iniciar sesión Name.com.vn',
            'login_email' => 'Correo electrónico de inicio de sesión',
            'password' => 'Contraseña',
            'remember_me' => 'Recuérdame',
            'login' => 'Iniciar sesión',
            'or_login_with' => 'O iniciar sesión con',
            'support' => 'Soporte',
            'download_guide' => 'Guía de descarga',
            'account_information' => 'Información de la cuenta',
            'my_downloads' => 'Mis descargas',
            'logout' => 'Cerrar sesión',
            'article' => "Artículo",
            'featured_articles' => 'Artículos Destacados',
            'news_category' => 'Categoría de Noticias',
            'payment_successful' => "¡Pago exitoso!",
            'thank_you_message' => "Gracias por apoyar a Name.com.vn. Su imagen está a continuación, o puede consultar su correo electrónico para descargar la imagen.",
            'order_id' => "Número de pedido",
            'email' => "Correo electrónico",
            'click_to_download' => "Haga clic para descargar",
            'step_1_buy_now' => "Paso 1: Por favor, ingrese su correo electrónico.",
            'note_fill_email' => "* Si ingresa un correo electrónico, se enviará una copia adicional para su almacenamiento.",
            'step_2_buy_now' => "Paso 2: Elija una forma de pago.",
            'what_do_you_want_to_find_today' => "¿Qué quieres buscar hoy?",
            'search' => "Buscar",
            /* xác nhận đơn hàng */
            'order_confirmation' => 'Confirmación de Pedido',
            'thank_you_message_email' => '¡Gracias por completar tu pedido! Tu fondo de pantalla está listo para usar.',
            'hello' => 'Hola',
            'purchase_date' => 'Fecha de compra',
            'download_instructions' => 'Puede descargar la colección de fondos de las siguientes maneras:',
            'direct_download' => 'Descarga directa a través de los enlaces a continuación:',
            'sincerely' => '¡Sinceramente!',
            'login_instruction_message_email' => 'O inicie sesión en <a href="https://name.com.vn" style="color: #006d57; text-decoration: none; font-weight: 700;">Name.com.vn</a> con su correo electrónico y vaya a la sección <strong>"Mis Descargas"</strong>.',
            'support_contact_message_email' => 'Si tiene alguna pregunta o necesita ayuda, por favor contáctenos por correo electrónico a <a href="mailto:wallpaperdienthoai@gmail.com" style="color: #006d57; text-decoration: none; font-weight: 700;">wallpaperdienthoai@gmail.com</a>.',
            'wish_message_email' => '¡Le deseamos una excelente experiencia con su nueva colección de fondos de pantalla!',
            /* custom */
            "wallpaper_theme" => [
                "name" => "Tema de fondo de pantalla",
                "topgirl" => "Tema de foto",
                "topanime" => "Tema de foto",
            ],
            "wallpaper_style" => [
                "name" => "Estilo de fondo de pantalla",
                "topgirl" => "Estilo de foto",
                "topanime" => "Estilo de foto",
            ],
            "free_wallpaper" => [
                "name" => "Fondo de pantalla gratis",
                "topgirl" => "Foto gratis",
                "topanime" => "Foto gratis",
            ],
            "phone_wallpaper" => [
                "name"      => "Fondo de pantalla para teléfono ",
                "topgirl"   => "Imágenes de chicas bonitas ",
                "topanime"  => "Imágenes de chicas bonitas ",
            ],
            "product_description" => [
                "name" => "<div>¡Transforma el fondo de pantalla de tu teléfono en una obra de arte con esta impresionante colección de fotos! Aporta un estilo fresco y único a tu teléfono.</div>
                            <ul>
                                <li>Alta resolución: 1440x3360, asegurando imágenes nítidas en cada detalle.</li>
                                <li>Perfectamente compatible con todo tipo de pantallas de teléfonos.</li>
                                <li>Descarga fácil y rápida en solo unos pocos pasos.</li>
                                <li>Incluye derechos de uso, siéntete libre de compartirlo con tus amigos.</li>
                            </ul>
                            <div>¡Descárgalo ahora y experimenta la emocionante diferencia en la pantalla de tu teléfono!</div>",
                "topgirl" => "<div>Añade color y un estilo único a tu lindo teléfono con este hermoso conjunto de fondos de pantalla para teléfono.</div>
                                <ul>
                                    <li>Resolución: 1440x3360</li>
                                    <li>Compatible con todas las pantallas de teléfonos.</li>
                                </ul>
                                <div>¡Descárgalo y aplícalo directamente en la pantalla de tu teléfono para probarlo!</div>",
                "topanime" => "<div>Añade color y un estilo único a tu lindo teléfono con este hermoso conjunto de fondos de pantalla para teléfono.</div>
                                <ul>
                                    <li>Resolución: 1440x3360</li>
                                    <li>Compatible con todas las pantallas de teléfonos.</li>
                                </ul>
                                <div>¡Descárgalo y aplícalo directamente en la pantalla de tu teléfono para probarlo!</div>",
            ],
            "wallpaper_by_themes" => [
                "name" => "Fondos de pantalla por temas",
                "topgirl" => "Fotos de chicas bonitas por temas",
                "topanime" => "Fotos de chicas bonitas por temas",
            ],
            "wallpaper_by_styles" => [
                "name" => "Fondos de pantalla por estilos",
                "topgirl" => "Fotos de chicas bonitas por estilos",
                "topanime" => "Fotos de chicas bonitas por estilos",
            ],
            "wallpaper_by_events" => [
                "name" => "Fondos de pantalla por eventos",
                "topgirl" => "Fotos de chicas bonitas por eventos",
                "topanime" => "Fotos de chicas bonitas por eventos",
            ],
            "list_type_search" => [
                'wrpfvietnam' => [
                    'category_info' => 'Categoría',
                    'paid_wallpaper' => 'Fondos de pantalla de pago',
                    'free_wallpaper' => 'Fondos de pantalla gratis',
                    'article' => 'Artículo',
                ],
                'topgirl' => [
                    'category_info' => 'Categoría',
                    'paid_wallpaper' => 'Fondos de pantalla de pago',
                    'free_wallpaper' => 'Fondos de pantalla gratis',
                    'article' => 'Artículo',
                ],
                'topanime' => [
                    'category_info' => 'Categoría',
                    'paid_wallpaper' => 'Fondos de pantalla de pago',
                    'free_wallpaper' => 'Fondos de pantalla gratis',
                    'article' => 'Artículo',
                ],
            ],
            "copyright" => [
                "name"  => "Derechos de autor ® ".date('Y')." <a href='{{ env('APP_URL') }}/{{ \$language }}' aria-label='Name'>Name</a>. Diseñado y desarrollado por Pham Van Phu. Todos los derechos reservados.",
            ]
        ]
    ],
    "fr" => [
        "name" => "Tiếng Pháp",
        "name_by_language" => "Français",
        "area" => "Pháp, Canada, Bỉ, Thụy Sĩ, các nước châu Phi",
        "scope" => "Ngôn ngữ phổ biến toàn cầu",
        "currency" => "EUR",
        "currency_code" => "€",
        "money_value" => "0.85",
        "decimal_places" => 2,
        "key" => "fr",
        "latin"     => true,
        "flag_join_left_to_right" => true,
        "flag_has_space_in_content" => true,
        "dir"       => "ltr",
        "slug_page_premium_wallpaper" => "fonds-d-ecran-pour-telephones",
        "data" => [
            "home" => "Accueil",
            "about_us" => "À propos de nous",
            "event" => "Événement",
            "support" => "Support",
            "connect_with_us" => "Connectez-vous avec nous",
            "table_of_contents" => "Table des matières",
            "photo_set" => "Ensemble de photos",
            "share" => "Partager",
            "no_suitable_results_found" => "Aucun résultat approprié trouvé",
            "cart" => "Panier",
            "your_cart_is_empty" => "Votre panier est vide",
            "continue_shopping" => "Continuer vos achats",
            "full_set" => "Ensemble complet",
            "image" => "Image",
            "options" => "Options",
            "product_guide_after_payment" => "<div>Après le paiement, vous recevrez l'image originale directement et par email pour téléchargement et utilisation.</div>",
            "suggestions_for_you" => "Suggestions pour vous!",
            "each_image" => "Chaque image",
            "each_set" => "Chaque ensemble",
            "propose" => "Proposer",
            "favourite" => "Favori",
            "newest" => "Le plus récent",
            "oldest" => "Le plus ancien",
            "browse_by" => "Parcourir par ",
            "sort_by" => "Trier par ",
            "filter_by" => "Filtrer par ",
            "filter_by_themes" => "Filtrer par thèmes",
            "filter_by_styles" => "Filtrer par styles",
            "filter_by_events" => "Filtrer par événements",
            "advanced_filter" => "Filtre avancé",
            "all" => "Tous",
            "added_to_cart" => "Ajouté au panier!",
            "view_cart" => "Voir le panier",
            "add_to_cart" => "Ajouter au panier",
            "buy_now" => "Acheter maintenant",
            "undefined" => "Indéfini",
            "total" => "Total",
            "remove_item_in_cart" => "Retirer l'article du panier",
            "product_list" => "Liste de produits",
            "product" => "Produit",
            "unit_price" => "Prix unitaire",
            "total_price" => "Prix total",
            "payment" => "Paiement",
            "information" => "Information",
            "email_prompt" => "Si vous entrez votre email, vous recevrez une copie supplémentaire pour stockage.",
            "email_receive" => "Email pour recevoir les images",
            "payment_method" => "Méthode de paiement",
            "fee" => "Frais",
            "payment_fee" => "Frais de paiement",
            'view_all' => 'Voir tout',
            'login_name_com_vn' => 'Connexion Name.com.vn',
            'login_email' => 'Email de connexion',
            'password' => 'Mot de passe',
            'remember_me' => 'Se souvenir de moi',
            'login' => 'Connexion',
            'or_login_with' => 'Ou se connecter avec',
            'support' => 'Support',
            'download_guide' => 'Guide de téléchargement',
            'account_information' => 'Informations du compte',
            'my_downloads' => 'Mes téléchargements',
            'logout' => 'Se déconnecter',
            'article' => "Article",
            'featured_articles' => 'Articles en Vedette',
            'news_category' => 'Catégorie de Nouvelles',
            'payment_successful' => "Paiement réussi!",
            'thank_you_message' => "Merci de soutenir Name.com.vn. Votre image est ci-dessous, ou vous pouvez consulter votre e-mail pour télécharger l'image.",
            'order_id' => "Numéro de commande",
            'email' => "E-mail",
            'click_to_download' => "Cliquez pour télécharger",
            'step_1_buy_now' => "Étape 1 : Veuillez entrer votre email.",
            'note_fill_email' => "* Si vous entrez un email, une copie supplémentaire sera envoyée pour archivage.",
            'step_2_buy_now' => "Étape 2 : Choisissez une méthode de paiement.",
            'what_do_you_want_to_find_today' => "Que voulez-vous chercher aujourd'hui ?",
            'search' => "Rechercher",
            /* xác nhận đơn hàng */
            'order_confirmation' => 'Confirmation de Commande',
            'thank_you_message_email' => 'Merci d\'avoir finalisé votre commande ! Votre fond d\'écran est prêt à être utilisé.',
            'hello' => 'Bonjour',
            'purchase_date' => 'Date d\'achat',
            'download_instructions' => 'Vous pouvez télécharger la collection de fonds d\'écran de la manière suivante :',
            'direct_download' => 'Téléchargement direct via les liens ci-dessous :',
            'sincerely' => 'Cordialement !',
            'login_instruction_message_email' => 'Ou connectez-vous à <a href="https://name.com.vn" style="color: #006d57; text-decoration: none; font-weight: 700;">Name.com.vn</a> avec votre e-mail et accédez à la section <strong>"Mes Téléchargements"</strong>.',
            'support_contact_message_email' => 'Si vous avez des questions ou besoin d\'aide, veuillez nous contacter par e-mail à <a href="mailto:wallpaperdienthoai@gmail.com" style="color: #006d57; text-decoration: none; font-weight: 700;">wallpaperdienthoai@gmail.com</a>.',
            'wish_message_email' => 'Nous vous souhaitons une excellente expérience avec votre nouvelle collection de fonds d\'écran!',
            /* custom */
            "wallpaper_theme" => [
                "name" => "Thème du fond d'écran",
                "topgirl" => "Thème de photo",
                "topanime" => "Thème de photo",
            ],
            "wallpaper_style" => [
                "name" => "Style du fond d'écran",
                "topgirl" => "Style de photo",
                "topanime" => "Style de photo",
            ],
            "free_wallpaper" => [
                "name" => "Fond d'écran gratuit",
                "topgirl" => "Photo gratuite",
                "topanime" => "Photo gratuite",
            ],
            "phone_wallpaper" => [
                "name" => "Fond d'écran pour téléphone ",
                "topgirl" => "Images de belles filles ",
                "topanime" => "Images de belles filles ",
            ],
            "product_description" => [
                "name" => "<div>Transformez le fond d'écran de votre téléphone en une œuvre d'art avec cette superbe collection de photos! Apportez un style frais et unique à votre téléphone.</div>
                            <ul>
                                <li>Haute résolution: 1440x3360, assurant des images nettes dans chaque détail.</li>
                                <li>Parfaitement compatible avec tous les types d'écrans de téléphone.</li>
                                <li>Téléchargement facile et rapide en quelques étapes simples.</li>
                                <li>Droits d'utilisation inclus, n'hésitez pas à partager avec vos amis.</li>
                            </ul>
                            <div>Téléchargez maintenant et découvrez la différence excitante sur l'écran de votre téléphone!</div>",
                "topgirl" => "<div>Ajoutez de la couleur et un style unique à votre joli téléphone avec ce magnifique ensemble de fonds d'écran pour téléphone.</div>
                                <ul>
                                    <li>Résolution: 1440x3360</li>
                                    <li>Compatible avec tous les écrans de téléphone.</li>
                                </ul>
                                <div>Téléchargez-le et appliquez-le directement sur l'écran de votre téléphone pour l'essayer!</div>",
                "topanime" => "<div>Ajoutez de la couleur et un style unique à votre joli téléphone avec ce magnifique ensemble de fonds d'écran pour téléphone.</div>
                                <ul>
                                    <li>Résolution: 1440x3360</li>
                                    <li>Compatible avec tous les écrans de téléphone.</li>
                                </ul>
                                <div>Téléchargez-le et appliquez-le directement sur l'écran de votre téléphone pour l'essayer!</div>",
            ],
            "wallpaper_by_themes" => [
                "name" => "Fonds d'écran par thèmes",
                "topgirl" => "Photos de belles filles par thèmes",
                "topanime" => "Photos de belles filles par thèmes",
            ],
            "wallpaper_by_styles" => [
                "name" => "Fonds d'écran par styles",
                "topgirl" => "Photos de belles filles par styles",
                "topanime" => "Photos de belles filles par styles",
            ],
            "wallpaper_by_events" => [
                "name" => "Fonds d'écran par événements",
                "topgirl" => "Photos de belles filles par événements",
                "topanime" => "Photos de belles filles par événements",
            ],
            "list_type_search" => [
                'wrpfvietnam' => [
                    'category_info' => 'Catégorie',
                    'paid_wallpaper' => 'Fonds d\'écran payants',
                    'free_wallpaper' => 'Fonds d\'écran gratuits',
                    'article' => 'Article',
                ],
                'topgirl' => [
                    'category_info' => 'Catégorie',
                    'paid_wallpaper' => 'Fonds d\'écran payants',
                    'free_wallpaper' => 'Fonds d\'écran gratuits',
                    'article' => 'Article',
                ],
                'topanime' => [
                    'category_info' => 'Catégorie',
                    'paid_wallpaper' => 'Fonds d\'écran payants',
                    'free_wallpaper' => 'Fonds d\'écran gratuits',
                    'article' => 'Article',
                ],
            ],
            "copyright" => [
                "name"  => "Droits d'auteur ® ".date('Y')." <a href='{{ env('APP_URL') }}/{{ \$language }}' aria-label='Name'>Name</a>. Conçu et développé par Pham Van Phu. Tous droits réservés.",
            ]
        ]
    ],
    "vi" => [
        "name" => "Tiếng Việt",
        "name_by_language" => "Tiếng Việt",
        "area" => "Việt Nam",
        "scope" => "Ngôn ngữ khu vực châu Á",
        "currency" => "Đ",
        "currency_code" => "đ",
        "money_value" => "25000",
        "decimal_places" => 0,
        "key" => "vi",
        "latin"     => true,
        "flag_join_left_to_right" => true,
        "flag_has_space_in_content" => true,
        "dir"       => "ltr",
        "slug_page_premium_wallpaper" => "hinh-nen-dien-thoai",
        "data"      => [
            "home"              => "Trang chủ",
            "about_us"          => "Về chúng tôi",
            "event"             => "Sự kiện",
            "support"           => "Hỗ trợ",
            "connect_with_us"   => "Kết nối với chúng tôi",
            "table_of_contents" => "Mục lục",
            "photo_set"         => "Bộ ảnh",
            "share"             => "Chia sẻ",
            "no_suitable_results_found" => "Không có kết quả phù hợp",
            "cart"              => "Giỏ hàng",
            "your_cart_is_empty"    => "Giỏ hàng của bạn trống",
            "continue_shopping" => "Tiếp tục mua sắm",
            "full_set"          => "Trọn combo",
            "image"             => "Ảnh",
            "options"           => "Tùy chọn",
            "product_guide_after_payment"   => "<div>Sau khi thanh toán, Bạn sẽ nhận được ảnh gốc trực tiếp và qua mail để có thể tải xuống sử dụng.</div>",
            "suggestions_for_you"   => "Gợi ý cho bạn!",
            "each_image"        => "Từng ảnh",
            "each_set"          => "Từng bộ",
            "propose" => "Đề xuất",
            "favourite" => "Yêu thích",
            "newest" => "Mới nhất",
            "oldest" => "Cũ nhất",
            "browse_by" => "Duyệt theo ",
            "sort_by" => "Sắp xếp theo ",
            "filter_by" => "Lọc theo ",
            "filter_by_themes" => "Lọc theo Chủ Đề",
            "filter_by_styles" => "Lọc theo Phong Cách",
            "filter_by_events" => "Lọc theo Sự Kiện",
            "advanced_filter" => "Bộ lọc nâng cao",
            "all" => "Tất cả",
            "added_to_cart" => "Đã thêm vào giỏ hàng!",
            "view_cart" => "Xem Giỏ Hàng",
            "add_to_cart" => "Thêm Giỏ Hàng",
            "buy_now" => "Mua Ngay",
            "undefined" => "Không xác định",
            "total" => "Tổng",
            "remove_item_in_cart" => "Xóa sản phẩm trong Giỏ Hàng",
            "product_list" => "Danh sách Sản Phẩm",
            "product" => "Sản Phẩm",
            "unit_price" => "Đơn Giá",
            "total_price" => "Thành Tiền",
            "payment" => "Thanh Toán",
            "information" => "Thông Tin",
            "email_prompt" => "Nếu nhập Email bạn sẽ được gửi thêm một bản để lưu trữ.",
            "email_receive" => "Email dùng nhận ảnh",
            "payment_method" => "Hình thức Thanh Toán",
            "fee" => "Phí",
            "payment_fee" => "Phí thanh toán",
            'view_all' => 'Xem tất cả',
            'login_name_com_vn' => 'Đăng nhập Name.com.vn',
            'login_email' => 'Email đăng nhập',
            'password' => 'Mật khẩu',
            'remember_me' => 'Ghi nhớ tôi',
            'login' => 'Đăng nhập',
            'or_login_with' => 'Hoặc đăng nhập với',
            'support' => 'Hỗ trợ',
            'download_guide' => 'Hướng dẫn tải',
            'account_information' => 'Thông tin tài khoản',
            'my_downloads' => 'Tải xuống của tôi',
            'logout' => 'Đăng xuất',
            'article' => "Bài viết",
            'featured_articles' => 'Bài viết nổi bật',
            'news_category' => 'Chuyên mục tin tức',
            'payment_successful' => "Thanh toán thành công!",
            'thank_you_message' => "Cảm ơn bạn đã ủng hộ Name.com.vn. Hình ảnh của bạn ở phần bên dưới hoặc bạn có thể truy cập email của mình để tải ảnh.",
            'order_id' => "Mã đơn",
            'email' => "Email",
            'click_to_download' => "Nhấn để tải",
            'step_1_buy_now' => "Bước 1: Bạn vui lòng nhập email.",
            'note_fill_email' => "* Nếu nhập email bạn sẽ được gửi thêm một bản để lưu trữ.",
            'step_2_buy_now' => "Bước 2: Chọn hình thức thanh toán.",
            'what_do_you_want_to_find_today' => "Bạn muốn tìm gì hôm nay?",
            'search' => "Tìm kiếm",
            /* xác nhận đơn hàng */
            'order_confirmation' => 'Xác nhận đơn hàng',
            'thank_you_message_email' => 'Cảm ơn bạn đã hoàn tất đơn hàng của mình! Hình nền của bạn đã sẵn sàng để sử dụng.',
            'hello' => 'Xin chào',
            'purchase_date' => 'Ngày mua',
            'download_instructions' => 'Bạn có thể tải bộ hình nền bằng các cách sau:',
            'direct_download' => 'Tải trực tiếp qua các liên kết bên dưới:',
            'sincerely' => 'Trân trọng!',
            'login_instruction_message_email' => 'Hoặc đăng nhập vào <a href="https://name.com.vn" style="color: #006d57; text-decoration: none; font-weight: 700;">Name.com.vn</a> bằng email của bạn và vào phần <strong>"Tải xuống của tôi"</strong>',
            'support_contact_message_email' => 'Nếu có bất kỳ thắc mắc hoặc cần hỗ trợ, vui lòng liên hệ với chúng tôi qua email: <a href="mailto:wallpaperdienthoai@gmail.com" style="color: #006d57; text-decoration: none; font-weight: 700;">wallpaperdienthoai@gmail.com</a>.',
            'wish_message_email' => 'Chúc bạn có những trải nghiệm tuyệt vời cùng bộ sưu tập hình nền mới của mình!',
            /* custom */
            "wallpaper_theme"   => [
                "name"  => "Chủ đề Hình Nền",
                "topgirl"  => "Chủ đề Ảnh",
                "topanime"  => "Chủ đề Ảnh",
            ],
            "wallpaper_style"   => [
                "name"  => "Phong cách Hình Nền",
                "topgirl"  => "Phong cách Ảnh",
                "topanime"  => "Phong cách Ảnh",
            ],
            "free_wallpaper"    => [
                "name"  => "Hình nền Miễn Phí",
                "topgirl"  => "Ảnh Miễn Phí",
                "topanime"  => "Ảnh Miễn Phí",
            ],
            "phone_wallpaper"   => [
                "name"  => "Hình nền điện thoại ",
                "topgirl"  => "Ảnh Gái Xinh ",
                "topanime"  => "Ảnh Anime ",
            ],
            "product_description"   => [
                "name"  => "<p>Biến màn hình nền điện thoại của bạn thành một tác phẩm nghệ thuật với bộ sưu tập ảnh tuyệt đẹp này! Đem lại phong cách mới lạ và sự tươi mới cho chiếc điện thoại của bạn.</p>
                                <ul>
                                    <li>Độ phân giải cao: 1440x3360, đảm bảo hình ảnh sắc nét đến từng chi tiết.</li>
                                    <li>Tương thích hoàn hảo với mọi loại màn hình điện thoại.</li>
                                    <li>Tải xuống dễ dàng và nhanh chóng chỉ với vài bước đơn giản.</li>
                                    <li>Đã bao gồm quyền sử dụng, bạn có thể thoải mái chia sẻ với bạn bè.</li>
                                </ul>
                                <div>Hãy tải ngay và cảm nhận sự khác biệt đầy thú vị trên màn hình điện thoại của bạn nhé!</div>
                            ",
                "topgirl"  => "<div>Thêm một chút màu sắc và phong cách độc đáo vào chiếc điện thoại xinh xắn của bạn với Bộ hình nền điện thoại tuyệt đẹp này.</div>
                                            <ul>
                                                <li>Độ phân giải: 1440x3360</li>
                                                <li>Tương thích tất cả màn hình điện thoại.</li>
                                            </ul>
                                            <div>Tải xuống áp dụng ngay trên màn hình điện thoại của bạn để cảm nhận nhé!</div>",
                "topanime"  => "<div>Thêm một chút màu sắc và phong cách độc đáo vào chiếc điện thoại xinh xắn của bạn với Bộ hình nền điện thoại tuyệt đẹp này.</div>
                                            <ul>
                                                <li>Độ phân giải: 1440x3360</li>
                                                <li>Tương thích tất cả màn hình điện thoại.</li>
                                            </ul>
                                            <div>Tải xuống áp dụng ngay trên màn hình điện thoại của bạn để cảm nhận nhé!</div>",
            ],
            "wallpaper_by_themes" => [
                "name"  => "Hình Nền Điện Thoại theo Chủ Đề",
                "topgirl"  => "Ảnh Gái Xinh theo Chủ Đề",
                "topanime"  => "Ảnh Anime theo Chủ Đề",
            ],
            "wallpaper_by_styles" => [
                "name"  => "Hình Nền Điện Thoại theo Phong Cách",
                "topgirl"  => "Ảnh Gái Xinh theo Phong Cách",
                "topanime"  => "Ảnh Anime theo Phong Cách",
            ],
            "wallpaper_by_events" => [
                "name"  => "Hình Nền Điện Thoại theo Sự Kiện",
                "topgirl"  => "Ảnh Gái Xinh theo Sự Kiện",
                "topanime"  => "Ảnh Anime theo Sự Kiện",
            ],
            "list_type_search" => [
                'wrpfvietnam' => [
                    'category_info' => 'Danh mục',
                    'paid_wallpaper' => 'Hình nền trả phí',
                    'free_wallpaper' => 'Hình nền miễn phí',
                    'article' => 'Bài viết',
                ],
                'topgirl' => [
                    'category_info' => 'Danh mục',
                    'paid_wallpaper' => 'Hình nền trả phí',
                    'free_wallpaper' => 'Hình nền miễn phí',
                    'article' => 'Bài viết',
                ],
                'topanime' => [
                    'category_info' => 'Danh mục',
                    'paid_wallpaper' => 'Hình nền trả phí',
                    'free_wallpaper' => 'Hình nền miễn phí',
                    'article' => 'Bài viết',
                ],
            ],
            "copyright" => [
                "name"  => "Bản quyền ® ".date('Y')." <a href='{{ env('APP_URL') }}/{{ \$language }}' aria-label='Name'>Name</a>. Thiết kế và phát triển bởi Phạm Văn Phú. Mọi quyền được bảo lưu.",
            ]
        ]
    ],
    "hi" => [
        "name" => "Tiếng Hindi",
        "name_by_language" => "हिंदी (Hindī)",
        "area" => "Ấn Độ",
        "scope" => "Ngôn ngữ khu vực châu Á",
        "currency" => "INR",
        "currency_code" => "₹",
        "money_value" => "82",
        "decimal_places" => 0,
        "key" => "hi",
        "latin"     => false,
        "flag_join_left_to_right" => true,
        "flag_has_space_in_content" => true,
        "dir"       => "ltr",
        "slug_page_premium_wallpaper" => "फोन-वॉलपेपर",
        "data" => [
            "home" => "होम",
            "about_us" => "हमारे बारे में",
            "event" => "इवेंट",
            "support" => "सहायता",
            "connect_with_us" => "हमसे जुड़ें",
            "table_of_contents" => "सामग्री की तालिका",
            "photo_set" => "फोटो सेट",
            "share" => "साझा करें",
            "no_suitable_results_found" => "कोई उपयुक्त परिणाम नहीं मिला",
            "cart" => "कार्ट",
            "your_cart_is_empty" => "आपका कार्ट खाली है",
            "continue_shopping" => "खरीदारी जारी रखें",
            "full_set" => "पूरा सेट",
            "image" => "छवि",
            "options" => "विकल्प",
            "product_guide_after_payment" => "<div>भुगतान के बाद, आपको डाउनलोड और उपयोग के लिए मूल छवि सीधे और ईमेल के माध्यम से प्राप्त होगी।</div>",
            "suggestions_for_you" => "आपके लिए सुझाव!",
            "each_image" => "प्रत्येक छवि",
            "each_set" => "प्रत्येक सेट",
            "propose" => "प्रस्ताव करें",
            "favourite" => "पसंदीदा",
            "newest" => "नवीनतम",
            "oldest" => "पुराने",
            "browse_by" => "के द्वारा ब्राउज़ करें ",
            "sort_by" => "के द्वारा सॉर्ट करें ",
            "filter_by" => "के द्वारा फ़िल्टर करें ",
            "filter_by_themes" => "थीम के द्वारा फ़िल्टर करें",
            "filter_by_styles" => "शैलियों के द्वारा फ़िल्टर करें",
            "filter_by_events" => "इवेंट्स के द्वारा फ़िल्टर करें",
            "advanced_filter" => "उन्नत फ़िल्टर",
            "all" => "सभी",
            "added_to_cart" => "कार्ट में जोड़ा गया!",
            "view_cart" => "कार्ट देखें",
            "add_to_cart" => "कार्ट में डालें",
            "buy_now" => "अभी खरीदें",
            "undefined" => "अनिर्धारित",
            "total" => "कुल",
            "remove_item_in_cart" => "कार्ट से आइटम हटाएं",
            "product_list" => "उत्पाद सूची",
            "product" => "उत्पाद",
            "unit_price" => "इकाई मूल्य",
            "total_price" => "कुल मूल्य",
            "payment" => "भुगतान",
            "information" => "सूचना",
            "email_prompt" => "यदि आप अपना ईमेल दर्ज करते हैं, तो आपको संग्रह के लिए एक अतिरिक्त प्रति प्राप्त होगी।",
            "email_receive" => "चित्र प्राप्त करने के लिए ईमेल",
            "payment_method" => "भुगतान का तरीका",
            "fee" => "शुल्क",
            "payment_fee" => "भुगतान शुल्क",
            'view_all' => 'सभी देखें',
            'login_name_com_vn' => 'लॉगिन Name.com.vn',
            'login_email' => 'लॉगिन ईमेल',
            'password' => 'पासवर्ड',
            'remember_me' => 'मुझे याद रखें',
            'login' => 'लॉगिन',
            'or_login_with' => 'या के साथ लॉगिन करें',
            'support' => 'सहायता',
            'download_guide' => 'डाउनलोड गाइड',
            'account_information' => 'खाता जानकारी',
            'my_downloads' => 'मेरे डाउनलोड',
            'logout' => 'लॉग आउट',
            'article' => "लेख",
            'featured_articles' => 'प्रमुख लेख',
            'news_category' => 'समाचार श्रेणी',
            'payment_successful' => "भुगतान सफल!",
            'thank_you_message' => "Name.com.vn का समर्थन करने के लिए धन्यवाद। आपकी छवि नीचे है, या आप छवि डाउनलोड करने के लिए अपने ईमेल की जांच कर सकते हैं।",
            'order_id' => "आदेश संख्या",
            'email' => "ईमेल",
            'click_to_download' => "डाउनलोड करने के लिए क्लिक करें",
            'step_1_buy_now' => "चरण 1: कृपया अपना ईमेल दर्ज करें।",
            'note_fill_email' => "* यदि आप ईमेल दर्ज करते हैं, तो भंडारण के लिए एक अतिरिक्त प्रति भेजी जाएगी।",
            'step_2_buy_now' => "चरण 2: भुगतान विधि चुनें।",
            'what_do_you_want_to_find_today' => "आज आप क्या खोजना चाहते हैं?",
            'search' => "खोज",
            /* xác nhận đơn hàng */
            'order_confirmation' => 'आर्डर की पुष्टि',
            'thank_you_message_email' => 'आपके ऑर्डर को पूरा करने के लिए धन्यवाद! आपका वॉलपेपर उपयोग के लिए तैयार है।',
            'hello' => 'नमस्ते',
            'purchase_date' => 'खरीद की तारीख',
            'download_instructions' => 'आप निम्नलिखित तरीकों से वॉलपेपर संग्रह डाउनलोड कर सकते हैं:',
            'direct_download' => 'नीचे दिए गए लिंक के माध्यम से सीधे डाउनलोड करें:',
            'sincerely' => 'सादर!',
            'login_instruction_message_email' => 'या अपनी ईमेल के साथ <a href="https://name.com.vn" style="color: #006d57; text-decoration: none; font-weight: 700;">Name.com.vn</a> में लॉग इन करें और <strong>"मेरे डाउनलोड"</strong> अनुभाग पर जाएं।',
            'support_contact_message_email' => 'यदि आपके कोई प्रश्न हैं या आपको सहायता की आवश्यकता है, तो कृपया हमें ईमेल के माध्यम से संपर्क करें: <a href="mailto:wallpaperdienthoai@gmail.com" style="color: #006d57; text-decoration: none; font-weight: 700;">wallpaperdienthoai@gmail.com</a>.',
            'wish_message_email' => 'हम आपको आपकी नई वॉलपेपर संग्रह के साथ शानदार अनुभव की कामना करते हैं!',
            /* custom */
            "wallpaper_theme" => [
                "name" => "वॉलपेपर थीम",
                "topgirl" => "फोटो थीम",
                "topanime" => "फोटो थीम",
            ],
            "wallpaper_style" => [
                "name" => "वॉलपेपर शैली",
                "topgirl" => "फोटो शैली",
                "topanime" => "फोटो शैली",
            ],
            "free_wallpaper" => [
                "name" => "नि: शुल्क वॉलपेपर",
                "topgirl" => "नि: शुल्क फोटो",
                "topanime" => "नि: शुल्क फोटो",
            ],
            "phone_wallpaper" => [
                "name" => "फोन वॉलपेपर ",
                "topgirl" => "सुंदर लड़की की छवियाँ ",
                "topanime" => "सुंदर लड़की की छवियाँ ",
            ],
            "product_description" => [
                "name" => "<div>इस शानदार फोटो संग्रह के साथ अपने फोन के वॉलपेपर को कला का एक काम में बदलें! अपने फोन को एक ताजगी और अद्वितीय शैली लाएं।</div>
                            <ul>
                                <li>उच्च रिज़ॉल्यूशन: 1440x3360, प्रत्येक विवरण में तेज़ छवियों को सुनिश्चित करना।</li>
                                <li>सभी प्रकार की फोन स्क्रीन के साथ पूरी तरह से संगत।</li>
                                <li>कुछ सरल चरणों में आसान और त्वरित डाउनलोड।</li>
                                <li>उपयोग अधिकार शामिल, अपने दोस्तों के साथ साझा करने के लिए स्वतंत्र महसूस करें।</li>
                            </ul>
                            <div>अभी डाउनलोड करें और अपने फोन की स्क्रीन पर रोमांचक अंतर का अनुभव करें!</div>",
                "topgirl" => "<div>इस सुंदर फोन वॉलपेपर सेट के साथ अपने प्यारे फोन में कुछ रंग और अद्वितीय शैली जोड़ें।</div>
                                <ul>
                                    <li>रिज़ॉल्यूशन: 1440x3360</li>
                                    <li>सभी फोन स्क्रीन के साथ संगत।</li>
                                </ul>
                                <div>इसे डाउनलोड करें और इसे अनुभव करने के लिए सीधे अपने फोन स्क्रीन पर लागू करें!</div>",
                "topanime" => "<div>इस सुंदर फोन वॉलपेपर सेट के साथ अपने प्यारे फोन में कुछ रंग और अद्वितीय शैली जोड़ें।</div>
                                <ul>
                                    <li>रिज़ॉल्यूशन: 1440x3360</li>
                                    <li>सभी फोन स्क्रीन के साथ संगत।</li>
                                </ul>
                                <div>इसे डाउनलोड करें और इसे अनुभव करने के लिए सीधे अपने फोन स्क्रीन पर लागू करें!</div>",
            ],
            "wallpaper_by_themes" => [
                "name" => "थीम्स द्वारा वॉलपेपर",
                "topgirl" => "थीम्स द्वारा सुंदर लड़की की तस्वीरें",
                "topanime" => "थीम्स द्वारा सुंदर लड़की की तस्वीरें",
            ],
            "wallpaper_by_styles" => [
                "name" => "शैलियों द्वारा वॉलपेपर",
                "topgirl" => "शैलियों द्वारा सुंदर लड़की की तस्वीरें",
                "topanime" => "शैलियों द्वारा सुंदर लड़की की तस्वीरें",
            ],
            "wallpaper_by_events" => [
                "name" => "घटनाओं द्वारा वॉलपेपर",
                "topgirl" => "घटनाओं द्वारा सुंदर लड़की की तस्वीरें",
                "topanime" => "घटनाओं द्वारा सुंदर लड़की की तस्वीरें",
            ],
            "list_type_search" => [
                'wrpfvietnam' => [
                    'category_info' => 'श्रेणी',
                    'paid_wallpaper' => 'भुगतान की गई वॉलपेपर',
                    'free_wallpaper' => 'नि:शुल्क वॉलपेपर',
                    'article' => 'लेख',
                ],
                'topgirl' => [
                    'category_info' => 'श्रेणी',
                    'paid_wallpaper' => 'भुगतान की गई वॉलपेपर',
                    'free_wallpaper' => 'नि:शुल्क वॉलपेपर',
                    'article' => 'लेख',
                ],
                'topanime' => [
                    'category_info' => 'श्रेणी',
                    'paid_wallpaper' => 'भुगतान की गई वॉलपेपर',
                    'free_wallpaper' => 'नि:शुल्क वॉलपेपर',
                    'article' => 'लेख',
                ],
            ],
            "copyright" => [
                "name"  => "कॉपीराइट ® ".date('Y')." <a href='{{ env('APP_URL') }}/{{ \$language }}' aria-label='Name'>Name</a>। डिजाइन और विकास Pham Van Phu द्वारा। सर्वाधिकार सुरक्षित।",
            ]
        ]
    ],
    "ja" => [
        "name" => "Tiếng Nhật",
        "name_by_language" => "日本語 (Nihongo)",
        "area" => "Nhật Bản",
        "scope" => "Ngôn ngữ khu vực châu Á",
        "currency" => "JPY",
        "currency_code" => "¥",
        "money_value" => "110",
        "decimal_places" => 0,
        "key" => "ja",
        "latin"     => false,
        "flag_join_left_to_right" => false,
        "flag_has_space_in_content" => false,
        "dir"       => "ltr",
        "slug_page_premium_wallpaper" => "携帯電話の壁紙",
        "data"      => [
            "home"          => "ホーム",
            "about_us"      => "私たちに関しては",
            "event"             => "イベント",
            "support"           => "サポート",
            "connect_with_us"   => "お問い合わせ",
            "table_of_contents" => "目次",
            "photo_set"         => "写真セット",
            "share"             => "シェア",
            "no_suitable_results_found" => "適切な結果が見つかりませんでした",
            "cart"              => "カート",
            "your_cart_is_empty"    => "カートは空です",
            "continue_shopping"     => "買い物を続ける",
            "full_set"          => "フルセット",
            "image"             => "画像",
            "options"           => "オプション",
            "product_guide_after_payment"   => "<div>支払い後、オリジナル画像を直接およびメールでダウンロードおよび使用のために受け取ります。</div>",
            "suggestions_for_you"   => "あなたへの提案！",
            "each_image"        => "各画像",
            "each_set"          => "各セット",
            "propose" => "提案する",
            "favourite" => "お気に入り",
            "newest" => "最新",
            "oldest" => "最古",
            "browse_by" => "で閲覧 ",
            "sort_by" => "で並べ替え ",
            "filter_by" => "でフィルタ ",
            "filter_by_themes" => "テーマでフィルタ",
            "filter_by_styles" => "スタイルでフィルタ",
            "filter_by_events" => "イベントでフィルタ",
            "advanced_filter" => "高度なフィルタ",
            "all" => "すべて",
            "added_to_cart" => "カートに追加されました！",
            "view_cart" => "カートを見る",
            "add_to_cart" => "カートに追加",
            "buy_now" => "今買う",
            "undefined" => "未定義",
            "total" => "合計",
            "remove_item_in_cart" => "カートからアイテムを削除",
            "product_list" => "商品リスト",
            "product" => "商品",
            "unit_price" => "単価",
            "total_price" => "合計金額",
            "payment" => "支払い",
            "information" => "情報",
            "email_prompt" => "メールを入力すると、保存用のコピーが追加で受け取れます。",
            "email_receive" => "画像受信用メール",
            "payment_method" => "支払い方法",
            "fee" => "手数料",
            "payment_fee" => "支払い手数料",
            'view_all' => 'すべてを見る',
            'login_name_com_vn' => 'ログイン Name.com.vn',
            'login_email' => 'ログインメール',
            'password' => 'パスワード',
            'remember_me' => '私を覚えてますか',
            'login' => 'ログイン',
            'or_login_with' => 'または以下でログイン',
            'support' => 'サポート',
            'download_guide' => 'ダウンロードガイド',
            'account_information' => 'アカウント情報',
            'my_downloads' => '私のダウンロード',
            'logout' => 'ログアウト',
            'article' => "記事",
            'featured_articles' => '注目の記事',
            'news_category' => 'ニュースカテゴリー',
            'payment_successful' => "支払いに成功しました！",
            'thank_you_message' => "Name.com.vn のご利用ありがとうございます。画像は以下にあります。メールにアクセスして画像をダウンロードすることもできます。",
            'order_id' => "注文番号",
            'email' => "メール",
            'click_to_download' => "ダウンロードするにはクリックしてください",
            'step_1_buy_now' => "ステップ1：メールアドレスを入力してください。",
            'note_fill_email' => "* メールアドレスを入力すると、保管用に追加のコピーが送信されます。",
            'step_2_buy_now' => "ステップ2：支払い方法を選択してください。",
            'what_do_you_want_to_find_today' => "今日は何を探しますか？",
            'search' => "検索",
            /* xác nhận đơn hàng */
            'order_confirmation' => '注文確認',
            'thank_you_message_email' => 'ご注文を完了いただきありがとうございます！壁紙の使用準備が整いました。',
            'hello' => 'こんにちは',
            'purchase_date' => '購入日',
            'download_instructions' => '以下の方法で壁紙コレクションをダウンロードできます：',
            'direct_download' => '以下のリンクから直接ダウンロードしてください：',
            'sincerely' => 'よろしくお願いします！',
            'login_instruction_message_email' => 'または、あなたのメールで <a href="https://name.com.vn" style="color: #006d57; text-decoration: none; font-weight: 700;">Name.com.vn</a> にログインして、<strong>"マイダウンロード"</strong> セクションにアクセスしてください',
            'support_contact_message_email' => 'ご質問がある場合やサポートが必要な場合は、メールでご連絡ください: <a href="mailto:wallpaperdienthoai@gmail.com" style="color: #006d57; text-decoration: none; font-weight: 700;">wallpaperdienthoai@gmail.com</a>。',
            'wish_message_email' => '新しい壁紙コレクションで素晴らしい体験をお楽しみいただけることを願っています！',
            /* custom */
            "wallpaper_theme"  => [
                "name"  => "壁紙テーマ",
                "topgirl"  => "写真テーマ",
                "topanime"  => "写真テーマ",
            ],
            "wallpaper_style"   => [
                "name"  => "壁紙スタイル",
                "topgirl"  => "写真スタイル",
                "topanime"  => "写真スタイル",
            ],
            "free_wallpaper"    => [
                "name"  => "無料壁紙",
                "topgirl"  => "無料写真",
                "topanime"  => "無料写真",
            ],
            "phone_wallpaper"         => [
                "name"  => "携帯電話の壁紙 ",
                "topgirl"  => "美しい女の子の画像 ",
                "topanime"  => "美しい女の子の画像 ",
            ],
            "product_description"   => [
                "name"  => "<div>この素晴らしい写真コレクションで携帯電話の壁紙を芸術作品に変えましょう！新鮮でユニークなスタイルを携帯電話に持ち込みます。</div>
                                <ul>
                                    <li>高解像度：1440x3360、細部までシャープな画像を保証。</li>
                                    <li>すべての種類の携帯電話の画面に完全に対応。</li>
                                    <li>簡単で迅速なダウンロード、数ステップで完了。</li>
                                    <li>使用権が含まれており、友達と自由に共有できます。</li>
                                </ul>
                                <div>今すぐダウンロードして、携帯電話の画面でエキサイティングな違いを体験してください！</div>",
                "topgirl"  => "<div>この美しい携帯電話の壁紙セットで、かわいい携帯電話に色とユニークなスタイルを追加しましょう。</div>
                                            <ul>
                                                <li>解像度：1440x3360</li>
                                                <li>すべての携帯電話の画面に対応。</li>
                                            </ul>
                                            <div>ダウンロードして、直接携帯電話の画面に適用して体験してください！</div>",
                "topanime"  => "<div>この美しい携帯電話の壁紙セットで、かわいい携帯電話に色とユニークなスタイルを追加しましょう。</div>
                                            <ul>
                                                <li>解像度：1440x3360</li>
                                                <li>すべての携帯電話の画面に対応。</li>
                                            </ul>
                                            <div>ダウンロードして、直接携帯電話の画面に適用して体験してください！</div>",
            ],
            "wallpaper_by_themes" => [
                "name"  => "テーマ別壁紙",
                "topgirl"  => "テーマ別美しい女の子の写真",
                "topanime"  => "テーマ別美しい女の子の写真",
            ],
            "wallpaper_by_styles" => [
                "name"  => "スタイル別壁紙",
                "topgirl"  => "スタイル別美しい女の子の写真",
                "topanime"  => "スタイル別美しい女の子の写真",
            ],
            "wallpaper_by_events" => [
                "name"  => "イベント別壁紙",
                "topgirl"  => "イベント別美しい女の子の写真",
                "topanime"  => "イベント別美しい女の子の写真",
            ],
            "list_type_search" => [
                'wrpfvietnam' => [
                    'category_info' => 'カテゴリー',
                    'paid_wallpaper' => '有料壁紙',
                    'free_wallpaper' => '無料壁紙',
                    'article' => '記事',
                ],
                'topgirl' => [
                    'category_info' => 'カテゴリー',
                    'paid_wallpaper' => '有料壁紙',
                    'free_wallpaper' => '無料壁紙',
                    'article' => '記事',
                ],
                'topanime' => [
                    'category_info' => 'カテゴリー',
                    'paid_wallpaper' => '有料壁紙',
                    'free_wallpaper' => '無料壁紙',
                    'article' => '記事',
                ],
            ],
            "copyright" => [
                "name"  => "著作権 ® ".date('Y')." <a href='{{ env('APP_URL') }}/{{ \$language }}' aria-label='Name'>Name</a>。Pham Van Phu によるデザインと開発。全著作権所有。",
            ]
        ]
    ],
    "ko" => [
        "name" => "Tiếng Hàn",
        "name_by_language" => "한국어 (Hangug-eo)",
        "area" => "Hàn Quốc",
        "scope" => "Ngôn ngữ khu vực châu Á",
        "currency" => "KRW",
        "currency_code" => "₩",
        "money_value" => "1300",
        "decimal_places" => 0,
        "key" => "ko",
        "latin"     => false,
        "flag_join_left_to_right" => false,
        "flag_has_space_in_content" => true,
        "dir"       => "ltr",
        "slug_page_premium_wallpaper" => "휴대폰-배경화면",
        "data"      => [
            "home"          => "홈",
            "about_us"      => "회사 소개",
            "event"             => "이벤트",
            "support"           => "지원",
            "connect_with_us"   => "문의하기",
            "table_of_contents" => "목차",
            "photo_set"         => "사진 세트",
            "share"             => "공유",
            "no_suitable_results_found" => "적절한 결과를 찾을 수 없습니다",
            "cart"              => "장바구니",
            "your_cart_is_empty"    => "장바구니가 비어 있습니다",
            "continue_shopping"     => "쇼핑 계속하기",
            "full_set"          => "전체 세트",
            "image"             => "이미지",
            "options"           => "옵션",
            "product_guide_after_payment"   => "<div>결제 후, 원본 이미지를 직접 및 이메일로 받아 다운로드하고 사용할 수 있습니다.</div>",
            "suggestions_for_you"   => "당신을 위한 추천!",
            "each_image"        => "각 이미지",
            "each_set"          => "각 세트",
            "propose" => "제안하다",
            "favourite" => "즐겨찾기",
            "newest" => "최신",
            "oldest" => "최고령",
            "browse_by" => "로 둘러보기 ",
            "sort_by" => "로 정렬 ",
            "filter_by" => "로 필터링 ",
            "filter_by_themes" => "테마로 필터링",
            "filter_by_styles" => "스타일로 필터링",
            "filter_by_events" => "이벤트로 필터링",
            "advanced_filter" => "고급 필터",
            "all" => "전체",
            "added_to_cart" => "장바구니에 추가되었습니다!",
            "view_cart" => "장바구니 보기",
            "add_to_cart" => "장바구니에 추가",
            "buy_now" => "지금 구매",
            "undefined" => "정의되지 않음",
            "total" => "합계",
            "remove_item_in_cart" => "장바구니에서 항목 제거",
            "product_list" => "제품 목록",
            "product" => "제품",
            "unit_price" => "단가",
            "total_price" => "총 가격",
            "payment" => "결제",
            "information" => "정보",
            "email_prompt" => "이메일을 입력하면 추가 사본을 저장용으로 받을 수 있습니다.",
            "email_receive" => "이미지 수신 이메일",
            "payment_method" => "결제 방법",
            "fee" => "수수료",
            "payment_fee" => "결제 수수료",
            'view_all' => '모두 보기',
            'login_name_com_vn' => '로그인 Name.com.vn',
            'login_email' => '로그인 이메일',
            'password' => '비밀번호',
            'remember_me' => '나를 기억해',
            'login' => '로그인',
            'or_login_with' => '또는 다음으로 로그인',
            'support' => '지원',
            'download_guide' => '다운로드 가이드',
            'account_information' => '계정 정보',
            'my_downloads' => '내 다운로드',
            'logout' => '로그아웃',
            'article' => "기사",
            'featured_articles' => '주요 기사',
            'news_category' => '뉴스 카테고리',
            'payment_successful' => "결제가 성공적으로 완료되었습니다!",
            'thank_you_message' => "Name.com.vn을 지원해 주셔서 감사합니다. 아래에서 이미지를 확인하거나 이메일에서 다운로드할 수 있습니다.",
            'order_id' => "주문 번호",
            'email' => "이메일",
            'click_to_download' => "다운로드하려면 클릭하세요",
            'step_1_buy_now' => "단계 1: 이메일을 입력해 주세요.",
            'note_fill_email' => "* 이메일을 입력하면 보관용으로 추가 사본이 전송됩니다.",
            'step_2_buy_now' => "단계 2: 결제 방식을 선택하세요.",
            'what_do_you_want_to_find_today' => "오늘 무엇을 찾고 싶으세요?",
            'search' => "검색",
            /* xác nhận đơn hàng */
            'order_confirmation' => '주문 확인',
            'thank_you_message_email' => '주문을 완료해 주셔서 감사합니다! 벽지가 사용할 준비가 되었습니다.',
            'hello' => '안녕하세요',
            'purchase_date' => '구매 날짜',
            'download_instructions' => '다음 방법으로 배경화면 컬렉션을 다운로드할 수 있습니다:',
            'direct_download' => '아래 링크를 통해 직접 다운로드하세요:',
            'sincerely' => '감사합니다!',
            'login_instruction_message_email' => '또는 이메일을 사용하여 <a href="https://name.com.vn" style="color: #006d57; text-decoration: none; font-weight: 700;">Name.com.vn</a>에 로그인하고 <strong>"내 다운로드"</strong> 섹션으로 이동하세요',
            'support_contact_message_email' => '질문이 있거나 도움이 필요하시면 이메일로 문의해 주세요: <a href="mailto:wallpaperdienthoai@gmail.com" style="color: #006d57; text-decoration: none; font-weight: 700;">wallpaperdienthoai@gmail.com</a>.',
            'wish_message_email' => '새로운 월페이퍼 컬렉션으로 멋진 경험을 하시길 바랍니다!',
            /* custom */
            "wallpaper_theme"  => [
                "name"  => "배경화면 테마",
                "topgirl"  => "사진 테마",
                "topanime"  => "사진 테마",
            ],
            "wallpaper_style"   => [
                "name"  => "배경화면 스타일",
                "topgirl"  => "사진 스타일",
                "topanime"  => "사진 스타일",
            ],
            "free_wallpaper"    => [
                "name"  => "무료 배경화면",
                "topgirl"  => "무료 사진",
                "topanime"  => "무료 사진",
            ],
            "phone_wallpaper"         => [
                "name"  => "휴대폰 배경화면 ",
                "topgirl"  => "아름다운 소녀 이미지 ",
                "topanime"  => "아름다운 소녀 이미지 ",
            ],
            "product_description"   => [
                "name"  => "<div>이 멋진 사진 컬렉션으로 휴대폰 배경화면을 예술 작품으로 변환하십시오! 신선하고 독특한 스타일을 휴대폰에 가져오세요.</div>
                                <ul>
                                    <li>고해상도: 1440x3360, 모든 세부 사항이 선명한 이미지를 보장합니다.</li>
                                    <li>모든 유형의 휴대폰 화면과 완벽하게 호환됩니다.</li>
                                    <li>몇 가지 간단한 단계로 쉽게 빠르게 다운로드할 수 있습니다.</li>
                                    <li>사용 권한이 포함되어 있으며, 친구와 자유롭게 공유할 수 있습니다.</li>
                                </ul>
                                <div>지금 다운로드하여 휴대폰 화면에서 흥미로운 차이를 경험하십시오!</div>",
                "topgirl"  => "<div>이 아름다운 휴대폰 배경화면 세트로 귀여운 휴대폰에 색상과 독특한 스타일을 추가하세요.</div>
                                            <ul>
                                                <li>해상도: 1440x3360</li>
                                                <li>모든 휴대폰 화면과 호환됩니다.</li>
                                            </ul>
                                            <div>다운로드하여 휴대폰 화면에 직접 적용해보세요!</div>",
                "topanime"  => "<div>이 아름다운 휴대폰 배경화면 세트로 귀여운 휴대폰에 색상과 독특한 스타일을 추가하세요.</div>
                                            <ul>
                                                <li>해상도: 1440x3360</li>
                                                <li>모든 휴대폰 화면과 호환됩니다.</li>
                                            </ul>
                                            <div>다운로드하여 휴대폰 화면에 직접 적용해보세요!</div>",
            ],
            "wallpaper_by_themes" => [
                "name"  => "테마별 배경화면",
                "topgirl"  => "테마별 아름다운 소녀 사진",
                "topanime"  => "테마별 아름다운 소녀 사진",
            ],
            "wallpaper_by_styles" => [
                "name"  => "스타일별 배경화면",
                "topgirl"  => "스타일별 아름다운 소녀 사진",
                "topanime"  => "스타일별 아름다운 소녀 사진",
            ],
            "wallpaper_by_events" => [
                "name"  => "이벤트별 배경화면",
                "topgirl"  => "이벤트별 아름다운 소녀 사진",
                "topanime"  => "이벤트별 아름다운 소녀 사진",
            ],
            "list_type_search" => [
                'wrpfvietnam' => [
                    'category_info' => '카테고리',
                    'paid_wallpaper' => '유료 배경화면',
                    'free_wallpaper' => '무료 배경화면',
                    'article' => '기사',
                ],
                'topgirl' => [
                    'category_info' => '카테고리',
                    'paid_wallpaper' => '유료 배경화면',
                    'free_wallpaper' => '무료 배경화면',
                    'article' => '기사',
                ],
                'topanime' => [
                    'category_info' => '카테고리',
                    'paid_wallpaper' => '유료 배경화면',
                    'free_wallpaper' => '무료 배경화면',
                    'article' => '기사',
                ],
            ],
            "copyright" => [
                "name"  => "저작권 ® ".date('Y')." <a href='{{ env('APP_URL') }}/{{ \$language }}' aria-label='Name'>Name</a>. Pham Van Phu에 의해 디자인 및 개발되었습니다. 모든 권리 보유.",
            ]
        ]
    ],
];